version: '3.8'

services:

  phoenix:
    container_name: phoenix
    build:
      context: ./phoenix
    ports:
      - '9000:9740'

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: djahwork_wallet
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4406:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - '5306:80'

  php-wallet:
    container_name: php-wallet
    build:
      context: ./php
    ports:
      - '9400:9400'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - db

  nginx-wallet:
    container_name: nginx-wallet
    image: nginx:stable-alpine
    ports:
      - '8888:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-wallet
      - db
